.travis.yml
FIx these warnings on travis build config:
[warn] on root: deprecated key: "sudo" (The key `sudo` has no effect anymore.)
=> [ci] Fix travis build config warning

.travis.yml, CHANGES.rst, openwisp_network_topology/__init__.py, requirements.txt
Verison 0.3.0 [2020-02-06]
--------------------------
- Dropped support python 3.5 and below
- Dropped support django 2.1 and below
- Dropped support openwisp-users below 0.2.0
- Dropped support openwisp-utils 4.1.0 and below
- Dropped support django-netjsongraph below 0.6.0
- Added support for django 3.0
Signed-off-by: Ajay Tripathi <ajay39in@gmail.com>
**Blocked by: django-netjsongraph 0.6.0 PyPi release**
=> 0.3.0 release

CHANGES.rst, openwisp_network_topology/__init__.py, requirements.txt
Verison 0.3.1 [2020-02-26]
--------------------------
- bumped min openwisp-utils 0.4.3
- bumped django-netjsongraph 0.6.1
Signed-off-by: Ajay Tripathi <ajay39in@gmail.com>
=> 0.3.1 release

.travis.yml, CHANGES.rst, openwisp_network_topology/__init__.py
- Merged openwisp-network-topology & django-netjsongraph
- [**breaking change**]: URLS at ``/api/`` moved to ``/api/v1/``
- [docs] Reordered & Improved docs
- Added requirement swapper~=1.1
- [docs] Added tutorial for extending openwisp-network-topology
- added upgrader script to upgrade from django-netjsongraph to openwisp-network-topology
- add support for netdiff~=0.8.0
Signed-off-by: Ajay Tripathi <ajay39in@gmail.com>
=> release 0.4.0

openwisp_network_topology/api/views.py, openwisp_network_topology/tests/test_admin.py, openwisp_network_topology/tests/test_api.py, openwisp_network_topology/utils.py
Closed issue by renaming /receive/{id}/ to /topology/{id}/receive/
while ensuring backward compatibility with warnings.
Closes #62
=> [api] /receive/{id}/ > /topology/{id}/receive/ #62

openwisp_network_topology/integrations/device/tests.py
Integration test for openwisp-monitoring was failing due to
re-registering of existing notification types. The test started
failing after introducing notifications support in
openwisp-controller.
The test is now adapted for new changes by mocking
"openwisp_notification.types.NOTIFICATION_TYPES"
=> [chores] Adapted integration test for openwisp-monitoring

openwisp_network_topology/base/link.py, openwisp_network_topology/integrations/device/tests.py
Link and Node in `setup()` of test class belongs to different topologies,
Added validation method in `AbstractLink` class to handle this case, Fixes #131
=> [fix] Link and Node should belong to same topologies #131

openwisp_network_topology/tests/test_admin.py, openwisp_network_topology/tests/test_topology.py
- Used openwisp-utils `@capture_any_output()` to avoid noisy error logging output during tests, Closes #132
=> [test] Avoided noisy error logging during tests #132

openwisp_network_topology/integrations/device/tests.py
Due to https://github.com/openwisp/openwisp-monitoring/pull/346
`create_database()` was removed from class `MonitoringConfig`
In result, it raises `AttributeError`, Therefore we need to update this testcase.
Closes #136
=> [test] Updated TestMonitoringIntegration #136

openwisp_network_topology/admin.py
For some reason the organization field in the topology list ended up in last position which is not consistent with the rest of the system.
=> [chores] Moved organization field in topology list admin to 2nd position

openwisp_network_topology/routing.py, openwisp_network_topology/tests/test_websockets.py
The `openwisp_network_topology/rounting.py` was missing a websocket path for non-admin view, which caused a `ValueError` to be raised with the message "No route found for path `'topology/topology/<topology:pk>/`"
Fixes #167
=> [fix] Fixed missing websocket path for non-admin view

openwisp_network_topology/tests/test_selenium.py, requirements-test.txt
=> [tests] Added for selenium tests for opening visualizers #165

README.rst, openwisp_network_topology/api/filters.py, openwisp_network_topology/api/views.py, openwisp_network_topology/tests/test_api.py
Now that the multitenant django-filters PR has been merged (https://github.com/openwisp/openwisp-users/pull/347), we can switch to using the multitenant version of `django-filters` in the API filters here.
Closes #180
=> [api/change] Migrated to openwisp-users REST API filters #180

openwisp_network_topology/tests/test_selenium.py, requirements-test.txt
Upgraded the selenium dependency to match the recent upgrade in `openwisp-controller` at commit https://github.com/openwisp/openwisp-controller/commit/b05c87528ec436b773be1e3edf7c5f7d45a18fe0 now we don't require pinning urllib3 to version 1.x in our project requirements (https://github.com/openwisp/openwisp-network-topology/commit/de2057163603a3d9124b71c70986c68a35b32a48).
=> [deps] Upgraded selenium

openwisp_network_topology/templates/netjsongraph/netjsongraph-script.html
The previous patch in #176 did an asynchronous request to fetch NetJSONGraph data. If the request promise didn't resovle before initialization of the graph (i.e. it took a long time for a response), then the graph was initialized with the default graphConfig. This caused the logic added to disable layoutAnimation to become obsolete.
This patch fixes this issue by updating graphConfig in NetJSONGraph.onLoad.
Related to #176
=> [fix] Fix visualizer quirks with big topologies #176

openwisp_network_topology/static/netjsongraph/js/visualize.js, openwisp_network_topology/tests/test_selenium.py
=> [fix] Fixed "Esc" key close bug in the visualizer

openwisp_network_topology/static/netjsongraph/css/style.css, openwisp_network_topology/tests/test_selenium.py
=> [fix] Fixed non-admin view visualizer disappears on resizing the window #193

README.rst, openwisp_network_topology/admin.py, openwisp_network_topology/integrations/device/tests/test_wifi_mesh.py
Bug:
When WiFi Mesh integration is enabled, opening the topology add view was generating Server 500 Error. The issue was caused because the topology instance for the ModelForm didn't have primary key set.
Fix:
Do not show "receive_url" field on add view.
=> [fix] Fixed "receive_url" field in TopologyAdmin

tests/openwisp2/settings.py
- Included `nested_admin` app in the settings **INSTALLED_APP**.
=> [fix] Resolved `TemplateDoesNotExist` error on device page

openwisp_network_topology/integrations/device/overrides.py, openwisp_network_topology/integrations/device/tests/test_integration.py
The `get_name` method override resulted in a non user friendly table heading "Get name" as in the screenshot below.
=> [fix] Fixed get_name admin short description in device integration

requirements-test.txt, requirements.txt, setup.py
- Bumped openwisp-users~=1.1.0
- Bumped netdiff~=1.1.0
- Bumped django-flat-json-widget~=0.3.1
- Bumped openwisp-utils[celery]~=1.1.1
=> [deps] Upgraded users, utils, netdiff and django-flat-json-widget

.github/workflows/ci.yml, openwisp_network_topology/templates/netjsongraph/netjsongraph-script.html, openwisp_network_topology/tests/test_realtime.py, tests/openwisp2/settings.py
=> [fix] Real time updates on visualizer view
