openwisp/openwisp-network-topology

openwisp_network_topology/__init__.py, openwisp_network_topology/admin.py, openwisp_network_topology/apps.py, openwisp_network_topology/base/admin.py, openwisp_network_topology/tests/__init__.py, openwisp_network_topology/tests/test_admin.py, tests/urls.py
This PR attempts to solve #1 to an extent. As of now, all the fields in the admin seem to be fine. Just need to check the multitenant features now.
=> Add multitenancy to admin

openwisp_network_topology/apps.py, openwisp_network_topology/templates/admin/openwisp_network_topology/change_form.html, openwisp_network_topology/templates/admin/openwisp_network_topology/visualize.html, openwisp_network_topology/templates/admin/submit_line.html, openwisp_network_topology/urls.py, openwisp_network_topology/visualizer/urls.py, openwisp_network_topology/visualizer/views.py
References #6. As of now, nothing has been done. Just added the django_netjsongraph dev to travis build and a test visualizer app.
=> Integrate visualizer into the application

.travis.yml, openwisp_network_topology/management/commands/update_topology.py, openwisp_network_topology/models.py, openwisp_network_topology/tests/__init__.py, openwisp_network_topology/tests/test_admin.py, openwisp_network_topology/tests/test_api.py, openwisp_network_topology/tests/test_utils.py, requirements-test.txt, tests/settings.py
This is just a test PR which aims to debug the Receive API. References #13
=> Production bug fixes

README.rst
The README was missing a conf parameter
=> missing configuration parameter

.travis.yml, openwisp_network_topology/models.py, tests/urls.py
This contains a temporary fix for the error in openwisp-users by installing it from github directly
=> [travis] Added django 2.0 to tests

.travis.yml
Can be merged after https://github.com/openwisp/openwisp-users/pull/19 is merged.
=> [qa] Added pending migration check to .travis.yml

.travis.yml, requirements-test.txt, runflake8, runisort, setup.cfg
Clean isort, flake and add commit style check
Fixes #32 
Fixes #30
=> [qa] Cleanup isort and flake8 settings in an OpenWISP module #30

.travis.yml, openwisp_network_topology/migrations/0005_default_operator_permission.py, setup.cfg
=> [migration] Added default operator permission #29

openwisp_network_topology/migrations/0006_reformat_addresses.py
=> [Node] Added data migration to reformat addresses #18

.travis.yml
=> [network-topology] Add support for Django 2.2 #36

openwisp_network_topology/tests/test_admin.py
Related to https://github.com/openwisp/django-netjsongraph/pull/113
=> [tests] Added module attribute to TestAdmin

.gitignore, .travis.yml, README.rst
1. Added `run-qa-checks` to Readme.
2. Added `Pipfile` and `.vscode` to `.gitignore`
3. `bash run-qa-checks` -> `./run-qa-checks`
=> [minor] Minor improvements

.travis.yml, CHANGES.rst, openwisp_network_topology/__init__.py, requirements-test.txt, requirements.txt
- [add] Support for openwisp-utils~=0.5.0
- [fix] swagger API fix for serializer
=> 0.3.2 release

.gitignore, README.rst, openwisp_network_topology/management/commands/upgrade_from_django_netjsongraph.py, openwisp_network_topology/tests/static/upgrader_script/contenttype.json, openwisp_network_topology/tests/static/upgrader_script/group.json, openwisp_network_topology/tests/static/upgrader_script/netjsongraph.json, openwisp_network_topology/tests/static/upgrader_script/permission.json, openwisp_network_topology/tests/static/upgrader_script/user.json, openwisp_network_topology/tests/test_upgrader_script.py, tests/openwisp2/sample_network_topology/management/commands/upgrade_from_django_netjsongraph.py, tests/openwisp2/sample_network_topology/tests.py
Related to https://github.com/openwisp/django-netjsongraph/pull/131
=> [enchancement] Add django-netjsongraph upgrader script

openwisp_network_topology/integrations/device/tests.py, requirements-test.txt
Fixed issue by adding openwisp_notifications
to TestMonitoringIntegration.
Fixes #82
=> [bug] Fix failing test #82

tests/openwisp2/settings.py
[tests] Added flat_json_widget to settings.py
=> [tests] Added flat_json_widget to settings.py

.travis.yml, requirements-test.txt, requirements.txt
Added support for django 3.1 + upgraded openwisp-utils to 0.6.
=> [deps] Added support for django 3.1 + upgraded openwisp-utils to 0.6

openwisp_network_topology/admin.py
Related to https://github.com/openwisp/ansible-openwisp2/issues/216
=> [fix] Removed static() call from media assets

openwisp_network_topology/api/views.py, openwisp_network_topology/tests/test_api.py, openwisp_network_topology/utils.py
=> remove deprecated api url #101

openwisp_network_topology/api/views.py, openwisp_network_topology/tests/test_api.py, requirements-test.txt, requirements.txt
=> [change] Implemented `DjangoModelPermissions` class #111

openwisp_network_topology/visualizer/views.py
=> [fix] Removed use of has_permission() #114

openwisp_network_topology/apps.py, openwisp_network_topology/static/netjsongraph/css/style.css, openwisp_network_topology/tests/test_admin.py
**Depends on**
I have added icons for this here.
https://github.com/openwisp/openwisp-utils/pull/226
closes #110
=> [enhancement] Registered menu groups #110

openwisp_network_topology/tests/test_admin.py
closes https://github.com/openwisp/openwisp-utils/issues/251
=> [test] Minor changes in test to fix failure

.github/workflows/ci.yml
Add new python runtime (3.9)
Fixes #120
=> [ci] Add new python runtime

openwisp_network_topology/migrations/0001_initial.py, openwisp_network_topology/migrations/0002_snapshot.py, openwisp_network_topology/migrations/0005_default_operator_permission.py, requirements.txt, tests/openwisp2/sample_network_topology/migrations/0001_initial.py, tests/openwisp2/settings.py
=> [fix] Migrations depend on swappable openwisp modules #122

.github/workflows/ci.yml, README.rst, openwisp_network_topology/admin.py, openwisp_network_topology/api/views.py, openwisp_network_topology/apps.py, openwisp_network_topology/base/link.py, openwisp_network_topology/base/node.py, openwisp_network_topology/base/snapshot.py, openwisp_network_topology/base/topology.py, openwisp_network_topology/integrations/device/apps.py, openwisp_network_topology/urls.py, openwisp_network_topology/utils.py, openwisp_network_topology/visualizer/views.py, requirements-test.txt, requirements.txt, tests/openwisp2/urls.py
- Dropped support for Django 2.2
- Added support for Django 3.2 and 4.0
- Pinned test dependencies
Closes #119
=> [deps] Updated support for Django #119 

tests/openwisp2/settings.py
=> [tests] Added openwisp-ipam in test project #126

openwisp_network_topology/tests/test_admin.py, requirements.txt, tests/openwisp2/sample_network_topology/migrations/0004_default_groups.py
Related to https://github.com/openwisp/openwisp-users/issues/106
=> [tests] Removed operator_permission_filters from tests

README.rst, openwisp_network_topology/api/serializers.py, openwisp_network_topology/api/views.py, openwisp_network_topology/tests/test_admin.py, openwisp_network_topology/tests/test_api.py, openwisp_network_topology/utils.py, tests/openwisp2/sample_network_topology/api/views.py, tests/openwisp2/sample_network_topology/tests.py, tests/openwisp2/settings.py
=> [api!] REST API for `openwisp-network-topology` module #109

README.rst, openwisp_network_topology/integrations/device/base/models.py, openwisp_network_topology/integrations/device/management/commands/__init__.py, openwisp_network_topology/integrations/device/tests.py
=> [feature] Added controller integration for wireguard #150

.github/workflows/ci.yml
Switched to openwisp-utils dev.
=> [ci] Upgrade pyopenssl lib to fix build error

openwisp_network_topology/admin.py, openwisp_network_topology/static/netjsongraph/css/src/netjsongraph.css
- jquery init was missing and causing a JS exception in list pages
- a couple netjsongraph CSS directives were operating on the entire layout instead of focusing on the netjsongraph overlay
=> [chores] Minor UI fixes

.github/workflows/ci.yml
Ubuntu 22.04, Django 3.2 and 4.0, Python 3.8, 3.9, 3.10.
=> [ci] Ubuntu 22.04, Django 3.2 and 4.0, Python 3.8, 3.9, 3.10

openwisp_network_topology/routing.py, openwisp_network_topology/templates/netjsongraph/netjsongraph-script.html, openwisp_network_topology/tests/test_websockets.py, openwisp_network_topology/visualizer/views.py
=> [change] Used single websocket route for both admin and non-admin #173

openwisp_network_topology/templates/netjsongraph/netjsongraph-script.html
=> [fix] Fix visualizer quirks with big topologies #164

openwisp_network_topology/consumers.py, openwisp_network_topology/tests/test_websockets.py, requirements-test.txt
=> [fix] Fixed consumer connection checking for unauthorized user #177

openwisp_network_topology/routing.py, openwisp_network_topology/templates/netjsongraph/netjsongraph-script.html, openwisp_network_topology/tests/test_websockets.py
WebSocket routes should start with "/ws/"
=> [fix] Fixed WebSocket routes

.github/workflows/ci.yml, tests/openwisp2/settings.py
Related to https://github.com/openwisp/openwisp-utils/pull/351 and https://code.djangoproject.com/ticket/32935.
=> [fix] Workaround for spatialite issue on Ubuntu 22.04 LTS

openwisp_network_topology/templates/netjsongraph/netjsongraph-script.html, openwisp_network_topology/tests/test_selenium.py
=> [fix] Fixed graph visualizer for unpublished topology in admin #169

openwisp_network_topology/static/netjsongraph/js/topology-history.js
Fixed issue caused by the changes which fixed #169.
=> [fix] Fixed topology history JS

tests/openwisp2/settings.py
Fixed CI build issues due to changes in latest versions of dependencies
=> [tests] Fixed CI build

openwisp_network_topology/admin.py, openwisp_network_topology/tests/test_admin.py
=> [fix] Admin actions require model permissions

.github/workflows/pypi.yml
=> [ci] Added workflow for PyPI publishing

CHANGES.rst, openwisp_network_topology/__init__.py
1.1.1 release
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
=> 1.1.1 release

.github/workflows/version-branch.yml, CHANGES.rst, openwisp_network_topology/__init__.py, requirements-test.txt, requirements.txt
=> [ci] Added GitHub workflow to replicate commits to version branch

.github/workflows/ci.yml, openwisp_network_topology/consumers.py, openwisp_network_topology/tests/test_websockets.py, openwisp_network_topology/tests/utils.py, requirements-test.txt, requirements.txt, tests/openwisp2/asgi.py, tests/openwisp2/settings.py
=> [deps] Upgraded Django 5.x and "channels" and "channels-test" extra requires

.github/workflows/pypi.yml, CHANGES.rst, README.rst, docs/developer/installation.rst, openwisp_network_topology/integrations/device/tests/test_wifi_mesh.py, openwisp_network_topology/templates/netjsongraph/netjsongraph-script.html, openwisp_network_topology/tests/test_selenium.py, requirements-test.txt, runtests.py
Various minor fixes to be released on 1.1 branch.
=> [chores] 1.1 fixes

.github/workflows/ci.yml, docs/developer/installation.rst, runtests, tests/openwisp2/settings.py
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
Let's make sure the instructions for running tests are up to date and easy to use.
=> [tests] Added runtests script, updated docs
